const loginFields = [
  {
    labelText: 'Email address',
    labelFor: 'email-address',
    id: 'email-address',
    name: 'email',
    type: 'email',
    autoComplete: 'email',
    isRequired: true,
    placeholder: 'Email address',
  },
  {
    labelText: 'Password',
    labelFor: 'password',
    id: 'password',
    name: 'password',
    type: 'password',
    autoComplete: 'current-password',
    isRequired: true,
    placeholder: 'Password',
  },
];

const signupFields = [
  {
    labelText: 'Username',
    labelFor: 'username',
    id: 'username',
    name: 'username',
    type: 'text',
    autoComplete: 'username',
    isRequired: true,
    placeholder: 'Username',
  },
  {
    labelText: 'Email address',
    labelFor: 'email-address',
    id: 'email-address',
    name: 'email',
    type: 'email',
    autoComplete: 'email',
    isRequired: true,
    placeholder: 'Email address',
  },
  {
    labelText: 'Password',
    labelFor: 'password',
    id: 'password',
    name: 'password',
    type: 'password',
    autoComplete: 'current-password',
    isRequired: true,
    placeholder: 'Password',
  },
  {
    labelText: 'Confirm Password',
    labelFor: 'confirm-password',
    id: 'confirm-password',
    name: 'confirm-password',
    type: 'password',
    autoComplete: 'confirm-password',
    isRequired: true,
    placeholder: 'Confirm Password',
  },
];

const recipeFields = [
  {
    labelText: 'title',
    labelFor: 'title',
    id: 'title',
    name: 'title',
    type: 'text',
    autoComplete: 'title',
    isRequired: true,
    placeholder: 'title',
  },
  {
    labelText: 'ingredients',
    labelFor: 'ingredients',
    id: 'ingredients',
    name: 'ingredients',
    type: 'textarea',
    autoComplete: 'ingredients',
    isRequired: true,
    placeholder: 'ingredients',
  },
  {
    labelText: 'recipeInstructions',
    labelFor: 'recipeInstructions',
    id: 'recipeInstructions',
    name: 'recipeInstructions',
    type: 'textarea',
    autoComplete: 'recipeInstructions',
    isRequired: true,
    placeholder: 'recipeInstructions',
  },
  {
    labelText: 'userId',
    labelFor: 'userId',
    id: 'userId',
    name: 'userId',
    type: 'text',
    autoComplete: 'userId',
    isRequired: true,
    placeholder: 'userId',
  },
]

export { loginFields, signupFields, recipeFields };
